services:
  db:
    image: postgres:17  # Changed from postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: statusframe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  pgdata:
